name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # TODO: This is a workaround. Switch to googleapis/release-please-action after
      #   https://github.com/googleapis/release-please/issues/2280 is fixed.
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # TODO: remove release-as after first release. Used to set the first
      #   release version, which would default to 1.0.0.
      # TODO: remove bump-minor-pre-major to reach 1.0.0. Otherwise
      #   major changes would be set as minor ones.
      - run: |
          npx release-please release-pr \
            --token="${{ secrets.REPO_PAT }}" \
            --repo-url="${{ github.repository }}" \
            --bump-minor-pre-major=true \
            --release-as=0.4.0 \
            --signoff "Francesco Canovai <francesco.canovai@enterprisedb.com>"

      #- uses: googleapis/release-please-action@v4
      #  id: release
      #  with:
      #    release-type: go
      #    token: ${{ secrets.REPO_PAT }}
      #    config-file: release-please-config.json
      #    manifest-file: .release-please-manifest.json
